### ISSUE TITLE
Improve metadata.

### ISSUE THREAD

**Issue by sophiekovalevsky** [prabhakar267/image-parser#13]
There is no meta data on the site. This will help us to be more friendly with web crawlers.

**Comment by prabhakar267** [comment]
@sophiekovalevsky can you please mention what kind of metadata you are talking about

**Comment by sophiekovalevsky** [comment]
@prabhakar267 sure.
I only noticed that you have the author name meta tag, which is not good. 
We could add the following, to give more details about the app:

<meta name="description" content="Put the content here">
<meta name="keywords" content="">
<meta property="og:site_name" content=""/>
<meta property="og:title" content=""/>
<meta property="og:url" content=""/>
<meta property="og:type" content="website"/>
<meta property="og:description" content="">
<meta property="og:image" content=""/>

This is just the beginning, so with that we can be more friendly for other apps and so on. 


What do you think?

**Comment by prabhakar267** [comment]
@sophiekovalevsky I was planning on changing the structure of files, to bring the sample UI in root directory and shift the API code to an API directory
I think your suggestions would be better than

**Comment by prabhakar267** [comment]
@sophiekovalevsky Can you go ahead and pick this issue?

**Comment by sophiekovalevsky** [comment]
@prabhakar267 for sure. I already create the pull request.

**Comment by sophiekovalevsky** [comment]
Done.
