### ISSUE TITLE
Move screenshots to a meta directory

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/image-parser#17]
Screenshots (https://github.com/prabhakar267/image-extractor/tree/master/assets/img/screenshot) should be moved a ```.github/screenshots``` directory which should be in the root of the project
Also update the readme URLs accrodingly

**Comment by GelaniNijraj** [comment]
I'll take care of this

**Comment by GelaniNijraj** [comment]
Pulled #19
Also, wouldn't it be better to directly just copy-paste the API response inside a code tag instead of putting the whole screenshot? Just a suggestion
