### ISSUE TITLE
Change extractor to parser

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/image-parser#18]
To have uniformity across whole repository, we can change the string "Extractor" to "Parser". There needs to a change in the following files:
```
README.md:Image Parser (or Image Extractor) is a web-application which extracts all the images on any public URL.
```

Also the file name (https://github.com/prabhakar267/image-extractor/blob/master/api/image-extractor.php) needs to be changed

**Comment by jsjqian** [comment]
Hi! I'm taking a look at this issue and I'm not sure exactly what needs to be done. Is the goal just to change the single instance of "Extractor" to "Parser" in the README.md and then change the file name? Are there any other areas that might also need to be changed?

**Comment by prabhakar267** [comment]
@jsjqian 
There needs to be a change in README and if there are any usages of "Extractor" in the whole code also the file name needs to be changed

**Comment by jsjqian** [comment]
So would you want an instance of "extract" be changed to "parse" as well or only when it is literally "Extractor"?
