### ISSUE TITLE
Remove parser code from index.php and make AJAX call to API

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/image-parser#23]
API is hosted at https://image-parser.herokuapp.com/api/image-parser.php
Instead of doing all the parsing in ```index.php``` we should make an AJAX call to the API and dynamically load all the results.

**Comment by nidble** [comment]
Hi @prabhakar267 ,

I'm working on this... ;-)

**Comment by prabhakar267** [comment]
Fixed in #31
