### ISSUE TITLE
Use CDNs for JQuery and Bootstrap instead of local files

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/image-parser#26]
Remove local files and use CDNs for faster page load. Links mentioned below can be used

jQuery: https://code.jquery.com/jquery-3.2.1.min.js
Bootstrap CSS: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
Bootstrap JS: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js

**Comment by aaronosher** [comment]
got this

**Comment by aaronosher** [comment]
#27
